#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Fixing autofixable ESLint errors/warnings.'

yarn lint:fix || 
(
     echo '😤🏀👋😤 Get that weak s**t out of here! 😤🏀👋😤 
                Types or Lint Check Failed. Make the required changes listed above, add changes and try to commit again.'
    false; 
)

# If everything passes... Now we can commit
echo '✅ Committing...'
